# ['21.68.36.55', '21.68.36.55']
# XIV Management IP Address in Area DevTest
---
- id: 01
  description: IBM XIV 01
  ipaddrs:
    - 192.168.1.1
    - 192.168.1.2

- id: 02
  description: IBM XIV 02
  ipaddrs:
    - 192.168.1.3
    - 192.168.1.4